name: Go CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20

    - name: Build
      run: |
        go build

    - name: Test
      run: |
        go test -v .

    - name: Coverage test
      run: |
        go tool cover -html=coverage.out ./...

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.out  # Ensure this is the correct path

